import axios, { AxiosError } from 'axios'
import { IncomingHttpHeaders, IncomingMessage } from 'http'
import type { NextPage, NextPageContext } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import getApiClient from '../api/get-client'
import styles from '../styles/Home.module.css'

interface CurrentUser {
  email: string;
  role: string;
  id: string
}

interface HomePageProps {
  currentUser?: CurrentUser
}

const Home: NextPage<HomePageProps> = ({ currentUser }: HomePageProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ticketing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>APP</h1>
        { currentUser ? <div className="user">{currentUser.email}</div> : null }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

Home.getInitialProps= async ({ req }) => {
  try {
    const client = getApiClient({ req });

    const { data: currentUser } = await client.get('/api/users/currentuser', { withCredentials: true });

    return { currentUser };
  } catch (error) {
    const axiosError = error as AxiosError;
    console.error(axiosError.response?.data);
    return { currentUser: null };
  }
}

export default Home
