version: "3.4"
services:
  ticketing-proxy:
    build:
      context: ./proxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - ticketing-auth
  ticketing-auth:
    build:
      context: ./auth
      target: debug
    volumes:
      - ./auth:/app
    ports:
      - 5000:5000
      - 9229:9229 #debug port
    environment:
      - DB_HOST=mongodb://mongodb:27017/users
      - JWT_SECRET=JO4zlH@zw%7p0A9bklP0v
      # - DB_NAME=users
      # - DB_USERNAME=root
      # - DB_PASSWORD=pass1234
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=pass12345
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      # - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      # - ME_CONFIG_MONGODB_ADMINPASSWORD=pass12345
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    ports:
      - 8081:8081
  ticketing-front:
    build:
      context: ./client
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
